name: "Feedback"
description: "Share feedback about the testing process, documentation, or findings."
title: "[Feedback] <short summary>"
labels: [feedback]
body:
  - type: markdown
    attributes:
      value: |
        ## Feedback
        Please provide your feedback below. This can be about the testing process, documentation, or anything else related to the project.
  - type: textarea
    id: feedback
    attributes:
      label: Feedback
      description: What feedback would you like to share?
      placeholder: "Describe your feedback here."
    validations:
      required: true
  - type: textarea
    id: suggestions
    attributes:
      label: Suggestions (optional)
      description: Any suggestions for improvement?
      placeholder: "Add suggestions here."
    validations:
      required: false